# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ajFPGcPkC3v7z1ucjQajpbWvWdyUwtOZ

# Task
Load and analyze the "/content/INvideos.csv" dataset by converting the 'publish_time' and 'trending_date' columns to datetime objects, calculating the 'time_to_trend' (the difference in hours between publishing and trending), and displaying the initial data inspection and the updated DataFrame.

## Environment Setup

### Subtask:
Import the necessary libraries for data analysis and visualization.

**Reasoning**:
Import the required libraries for data manipulation, visualization, and text analysis as specified in the subtask instructions.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from wordcloud import WordCloud, STOPWORDS

print("Libraries imported successfully.")

"""## Load Dataset

### Subtask:
Load the 'INvideos.csv' dataset into a pandas DataFrame and perform an initial inspection.

**Reasoning**:
Load the 'INvideos.csv' dataset using pandas and perform an initial inspection as specified in the subtask instructions.
"""

import pandas as pd

# Load the dataset
df = pd.read_csv('/content/INvideos.csv')

# Display the first five rows
print("First 5 rows:")
display(df.head())

# Print the shape of the DataFrame
print(f"\nDataFrame shape: {df.shape}")

# List the column names
print(f"\nColumns: {df.columns.tolist()}")

# Check data types and missing values
print("\nDataFrame Info:")
df.info()

"""## Date Formatting

### Subtask:
Convert the 'publish_time' and 'trending_date' columns into datetime objects to enable time-based calculations.

**Reasoning**:
I will convert the 'publish_time' and 'trending_date' columns to datetime objects using appropriate formats to ensure accurate time-based analysis as requested in the subtask instructions.
"""

import pandas as pd

# Convert 'publish_time' to datetime objects
# Standard ISO 8601 format usually handled automatically, but we ensure UTC awareness/handling
df['publish_time'] = pd.to_datetime(df['publish_time'])

# Convert 'trending_date' to datetime objects using the specific format YY.DD.MM
df['trending_date'] = pd.to_datetime(df['trending_date'], format='%y.%d.%m')

# Verify the conversion
print("Data types after conversion:")
print(df[['publish_time', 'trending_date']].dtypes)

# Display the first few rows to verify the values
display(df[['publish_time', 'trending_date']].head())

"""## Feature Engineering

### Subtask:
Calculate the difference between 'trending_date' and 'publish_time' in hours and store it in a new column called 'time_to_trend'.

**Reasoning**:
I will calculate the time difference in hours between 'trending_date' and 'publish_time' by handling the timezone mismatch and storing the result in a new column 'time_to_trend'.
"""

import pandas as pd

# Ensure publish_time is naive to match trending_date for subtraction
df['publish_time_naive'] = df['publish_time'].dt.tz_localize(None)

# Calculate the difference and convert to hours
# Using total_seconds() / 3600 for precision
df['time_to_trend'] = (df['trending_date'] - df['publish_time_naive']).dt.total_seconds() / 3600

# Drop the temporary naive column
df.drop(columns=['publish_time_naive'], inplace=True)

# Display the results
print("Time to trend calculation complete.")
display(df[['publish_time', 'trending_date', 'time_to_trend']].head())

# Check basic statistics of the new column
print("\nSummary statistics for 'time_to_trend':")
print(df['time_to_trend'].describe())

"""## Final Task

### Subtask:
Summarize the data processing steps and display the first few rows of the updated DataFrame to verify the new feature.

## Summary:

### Q&A
**How was the 'time_to_trend' metric calculated?**
The metric was calculated by converting both `publish_time` and `trending_date` into datetime objects. To ensure compatibility for subtraction, the timezone information from `publish_time` was removed. The difference between the two dates was then converted into total seconds and divided by 3,600 to obtain the duration in hours.

### Data Analysis Key Findings
*   **Dataset Overview:** The Indian YouTube trending videos dataset contains **37,352 entries** across 16 columns, including metrics like views, likes, and dislikes.
*   **Data Cleaning:** Initial string-based date columns were successfully reformatted. `publish_time` was converted to UTC datetime, and `trending_date` was parsed from a specific `YY.DD.MM` format.
*   **Trending Speed:** On average, a video in this dataset takes approximately **39 hours** to reach the trending page.
*   **Range of Performance:**
    *   The median time to trend is **33.6 hours**.
    *   The dataset shows significant variance, with some videos trending almost immediately while others took up to **5,283 hours** (roughly 220 days).
*   **Data Quality:** The dataset is highly complete; only the `description` column showed missing values (affecting roughly 1.5% of rows).

### Insights or Next Steps
*   **Analyze Outliers:** Investigate the videos that took over 1,000 hours to trend to determine if specific categories or late-blooming viral trends drive these extreme values.
*   **Correlation Analysis:** Compare the `time_to_trend` column with engagement metrics (likes and views) to see if faster-trending videos correlate with higher overall popularity.

# 2nd Engagement Relationships:

# Task
Analyze the engagement relationships within the "/content/INvideos.csv" dataset by performing the following steps:
1. **Analyze View-Engagement Relationships**: Create scatter plots using seaborn to visualize the relationships between 'views' vs 'likes' and 'views' vs 'comment_count'. Include regression lines to identify correlations and apply proper axis labels and titles.
2. **Calculate Engagement Rate**: Engineer a new feature called 'engagement_rate' calculated as the sum of 'likes' and 'comment_count' divided by 'views'.
3. **Visualize Engagement Rate Distribution**: Plot the distribution of the newly created 'engagement_rate' using a histogram or KDE plot to understand how engagement varies across the dataset.
4. **Summarize Findings**: Provide a summary of the findings from the engagement analysis, highlighting key correlations and insights from the engagement rate distribution.

## Analyze View-Engagement Relationships

### Subtask:
Create scatter plots with regression lines to visualize the relationships between views and engagement metrics (likes and comment counts).

**Reasoning**:
I will create the requested scatter plots with regression lines using seaborn's regplot to visualize the relationship between views and engagement metrics (likes and comment counts).
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Set the visual style
sns.set_style('whitegrid')

# Create a figure with two subplots
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Plot Views vs Likes
sns.regplot(x='views', y='likes', data=df, ax=axes[0], scatter_kws={'alpha':0.3}, line_kws={'color':'red'})
axes[0].set_title('Relationship Between Views and Likes')
axes[0].set_xlabel('Views')
axes[0].set_ylabel('Likes')

# Plot Views vs Comment Count
sns.regplot(x='views', y='comment_count', data=df, ax=axes[1], scatter_kws={'alpha':0.3}, line_kws={'color':'red'})
axes[1].set_title('Relationship Between Views and Comment Count')
axes[1].set_xlabel('Views')
axes[1].set_ylabel('Comment Count')

plt.tight_layout()
plt.show()

"""## Calculate Engagement Rate

### Subtask:
Engineer a new feature called 'engagement_rate' calculated as the sum of 'likes' and 'comment_count' divided by 'views'.

**Reasoning**:
I will engineer the 'engagement_rate' feature by summing 'likes' and 'comment_count' and dividing by 'views', while safely handling potential division by zero using a conditional check.
"""

import numpy as np

# Calculate engagement rate: (likes + comment_count) / views
# Using np.where to handle cases where views might be 0 to avoid division by zero
df['engagement_rate'] = np.where(
    df['views'] > 0,
    (df['likes'] + df['comment_count']) / df['views'],
    0
)

# Display the first few rows of the updated DataFrame for verification
print("Engagement rate feature engineered.")
display(df[['views', 'likes', 'comment_count', 'engagement_rate']].head())

# Check the distribution of the new column
print("\nBasic statistics for engagement_rate:")
print(df['engagement_rate'].describe())

"""**Reasoning**:
I will visualize the distribution of the newly created 'engagement_rate' using a histogram and a Kernel Density Estimate (KDE) plot to understand its spread and identify any common engagement patterns across the dataset.


"""

import matplotlib.pyplot as plt
import seaborn as sns

# Set the visual style
sns.set_style('whitegrid')

# Initialize the figure
plt.figure(figsize=(12, 6))

# Plot the distribution of engagement_rate
sns.histplot(df['engagement_rate'], bins=50, kde=True, color='teal')

# Add titles and labels
plt.title('Distribution of Engagement Rate', fontsize=15)
plt.xlabel('Engagement Rate (Likes + Comments / Views)', fontsize=12)
plt.ylabel('Frequency', fontsize=12)

# Adjust x-axis limits if there are extreme outliers to make the bulk of the data visible
# Based on statistics, most data is under 0.1
plt.xlim(0, 0.2)

plt.show()

"""## Final Task

### Subtask:
Summarize the findings from the engagement analysis, highlighting key correlations and insights from the engagement rate distribution.

## Summary:

### Q&A

**What is the relationship between video views and audience interaction?**
There is a strong, positive linear correlation between views and engagement metrics. As view counts increase, the number of likes and comments typically increases in a linear fashion, though most videos are clustered at the lower end of the spectrum.

**How is the engagement rate calculated and distributed?**
The engagement rate is calculated as the sum of likes and comments divided by views. The distribution is heavily right-skewed, with a mean of approximately 2.46% and a median of 1.08%, indicating that while most videos have modest interaction, a small number of videos achieve exceptionally high engagement relative to their size.

### Data Analysis Key Findings

*   **Strong Positive Correlation**: Regression analysis confirms that views are a strong predictor for both likes and comment counts, though the density of interaction varies across different videos.
*   **Engagement Benchmark**: The typical engagement rate (median) for the dataset is approximately **1.08%**.
*   **Skewed Performance**: The average engagement (**2.46%**) is more than double the median, driven by outliers with rates as high as **77.4%**.
*   **Common Interaction Range**: The majority of content in the dataset falls within an engagement rate of **0% to 5%**, with frequency dropping sharply beyond this range.
*   **Outlier Influence**: Transparency in scatter plots revealed that high-performing outliers significantly drive the overall trend lines, despite the majority of data points being clustered at lower view counts.

### Insights or Next Steps

*   **Content Strategy**: Investigate the videos in the top 5% of engagement rates to identify specific content characteristics (e.g., category, title keywords) that drive high interaction regardless of total view count.
*   **Outlier Analysis**: Perform a deep dive into videos with engagement rates exceeding 10% to determine if they represent viral niche content or potential data anomalies.

# 3rd Category Analysis:

# Task
Analyze the distribution and performance of video categories in the "/content/INvideos.csv" dataset by performing the following steps:
1. **Analyze Category Frequency**: Calculate the number of trending videos per category by grouping the data by 'category_id' and sorting the results in descending order.
2. **Visualize Top Categories**: Create a bar chart using seaborn to visualize the distribution of videos across different categories. Ensure the x-axis labels are rotated for better readability.
3. **Compare Average Views by Category**: Calculate and visualize the average view count for each category using a bar plot to identify which categories tend to attract the most viewership on average.
4. **Final Task**: Summarize the findings from the category analysis, highlighting the most frequent and the most-viewed categories.

## Analyze Category Frequency

### Subtask:
Calculate the frequency of trending videos for each category using 'category_id' and sort the results.

**Reasoning**:
I will calculate the frequency of trending videos by grouping the DataFrame by 'category_id', counting the occurrences, and sorting them in descending order.
"""

# Calculate the frequency of trending videos for each category
category_counts = df.groupby('category_id').size().sort_values(ascending=False)

# Convert to DataFrame for better visualization
category_counts_df = category_counts.reset_index(name='video_count')

# Print the result to inspect the frequency distribution
print("Frequency of trending videos per category_id:")
print(category_counts_df)

# Display basic statistics about category distribution
print(f"\nTotal unique categories: {len(category_counts_df)}")
print(f"Category with most trending videos: ID {category_counts_df.iloc[0]['category_id']} ({category_counts_df.iloc[0]['video_count']} videos)")

"""## Visualize Top Categories

### Subtask:
Create a bar chart using seaborn to visualize the distribution of trending videos across different categories based on the previously calculated frequencies.

**Reasoning**:
I will create a bar chart using seaborn to visualize the distribution of trending videos across categories as specified in the subtask instructions.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Set the figure size for better readability
plt.figure(figsize=(12, 6))

# Create the bar chart, assigning hue to x to avoid the FutureWarning and setting legend=False
sns.barplot(x='category_id', y='video_count', data=category_counts_df, hue='category_id', palette='viridis', legend=False)

# Set the title and labels
plt.title('Distribution of Videos across Different Categories', fontsize=15)
plt.xlabel('Category ID', fontsize=12)
plt.ylabel('Video Count', fontsize=12)

# Rotate the x-axis labels for better legibility
plt.xticks(rotation=45)

# Display the plot
plt.show()

"""## Compare Average Views by Category

### Subtask:
Calculate and visualize the average view count for each category using a bar plot to identify which categories tend to attract the most viewership on average.

**Reasoning**:
I will calculate the average views for each category by grouping the data by 'category_id', then I will visualize these averages using a seaborn bar plot as instructed.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Group by category_id and calculate mean views
avg_views_by_category = df.groupby('category_id')['views'].mean().sort_values(ascending=False).reset_index(name='mean_views')

# Set the figure size
plt.figure(figsize=(12, 6))

# Create the bar plot
sns.barplot(x='category_id', y='mean_views', data=avg_views_by_category, hue='category_id', palette='magma', legend=False)

# Add title and labels
plt.title('Average View Count by Category', fontsize=15)

plt.xlabel('Category ID', fontsize=12)
plt.ylabel('Average Views', fontsize=12)

# Rotate x-axis labels for readability
plt.xticks(rotation=45)

# Display the plot
plt.show()

# Display the resulting data for reference
print("Average views per category (sorted):")
print(avg_views_by_category)

"""## Summary of Category Analysis:

### Q&A

**Which category has the highest number of trending videos?**
Category ID **24** (Entertainment) significantly leads the dataset with over 16,000 trending videos, representing nearly 45% of the total entries.

**Do the most frequent categories also have the highest average views?**
No. While Category 24 is the most frequent, it ranks 7th in average views. Niche categories like **Category 20** (Gaming) and **Category 30** (Movies) attract much higher average viewership per video despite appearing less frequently in the trending list.

### Data Analysis Key Findings

*   **Volume Leader**: Category **24** is the dominant category in terms of frequency (16,712 videos), followed by Category **25** (News & Politics) and Category **10** (Music).
*   **High-Impact Categories**: Category **20** leads in average performance with approximately **4.16 million views** per trending video, followed by Category **30** (~3.06 million views).
*   **Long Tail**: Several categories like 15, 19, and 30 have very few trending videos (under 20 each), but some of these (like 20 and 30) exhibit extremely high average reach when they do trend.
*   **Consistency**: Music (Category 10) and Film & Animation (Category 1) show a strong balance of both high frequency and high average viewership.

### Insights or Next Steps

*   **Content Strategy**: For creators aiming for mass reach, Music and Entertainment are the most reliable entry points into trending, but Gaming (20) appears to have the highest 'viral' potential per video.
*   **Categorical Mapping**: A useful next step would be to map these Category IDs to their actual names (e.g., 'Entertainment', 'Music') using a JSON reference file to make the insights more accessible to non-technical stakeholders.

## Final Task

### Subtask:
Summarize the findings from the category analysis, highlighting the most frequent and the most-viewed categories.

## Summary:

### Q&A

**Which category has the highest number of trending videos?**  
Category ID **24** (Entertainment) is the most frequent, with **16,712** trending videos, making it the dominant content type in the Indian market.

**Do the categories with the most videos also get the most views?**  
No. While Category 24 has the highest volume, Category **20** (Gaming) leads in average viewership with approximately **4.16 million** views per video. This indicates that while some categories trend more often, others have higher "viral" potential per individual video.

### Data Analysis Key Findings

*   **Frequency Distribution**: The dataset features **17 unique categories**. Category **24** is the clear leader in frequency, followed by Category **25** (News & Politics) with 5,241 videos and Category **10** (Music) with 3,858 videos.
*   **Average Viewership Performance**: Category **20** (Gaming) ranks first in average engagement (~4.16M views), followed by Category **30** (~3.06M views) and Category **10** (Music) (~2.78M views).
*   **Volume vs. Impact**: Category 24 (the most frequent) ranks only 7th in terms of average views, suggesting that high-volume categories may face more competition or have more varied performance compared to high-impact niche categories.
*   **Low Representation**: Categories such as **15** (Pets & Animals) and **19** (Travel & Events) have the lowest representation, with fewer than 10 trending videos each in the dataset.

### Insights or Next Steps

*   **Strategic Content Focus**: Creators looking for high engagement should note that Category **10** (Music) offers a strong balance of high frequency and high average viewership, while Gaming and Movies offer the highest reach per post.
*   **Metadata Enrichment**: The next logical step is to map these `category_id` values to their actual names (e.g., mapping 24 to "Entertainment") using the associated JSON metadata to make the findings more actionable for non-technical stakeholders.

# 4th : Time to Trend Analysis

# Task
Analyze the timing distribution and upload patterns for the "/content/INvideos.csv" dataset by performing the following steps:
1. **Analyze Time to Trend Distribution**: Visualize the distribution of the existing 'time_to_trend' column using a histogram and KDE plot to understand the typical duration between publishing and trending.
2. **Analyze Publish Hour Frequency**: Extract the hour of the day from the 'publish_time' column and create a countplot to identify which hours of the day generate the most trending videos.
3. **Identify Optimal Upload Windows**: Group the data by the extracted publish hour to calculate the average 'time_to_trend' or average view counts, identifying potential 'best' upload time ranges for faster trending or higher reach.
4. **Final Task**: Summarize the findings from the timing analysis, highlighting the most common publish hours and the typical speed at which videos reach the trending page.

## Analyze Time to Trend Distribution

### Subtask:
Visualize the distribution of the existing 'time_to_trend' column using a histogram and KDE plot to understand the typical duration between publishing and trending.

**Reasoning**:
I will visualize the distribution of the 'time_to_trend' column using a histogram and KDE plot, applying a limit to the x-axis to focus on the most relevant data range as specified in the instructions.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Set the visual style
sns.set_style('whitegrid')

# Initialize a figure of appropriate size
plt.figure(figsize=(12, 6))

# Create a distribution plot for the 'time_to_trend' column
sns.histplot(df['time_to_trend'], bins=100, kde=True, color='skyblue')

# Add clear title and labels
plt.title('Distribution of Time to Trend', fontsize=15)
plt.xlabel('Hours from Publish to Trending', fontsize=12)
plt.ylabel('Frequency', fontsize=12)

# Apply x-axis limit to focus on the majority of the data (0-200 hours)
plt.xlim(0, 200)

# Display the plot
plt.show()

"""## Analyze Publish Hour Frequency

### Subtask:
Extract the hour of the day from the 'publish_time' column and visualize the frequency of trending videos by their upload hour.

**Reasoning**:
I will extract the 'publish_hour' from the 'publish_time' column and use a countplot to visualize the frequency of trending videos by their upload hour, as specified in the instructions.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Extract the hour from the 'publish_time' column
df['publish_hour'] = df['publish_time'].dt.hour

# 2. Set the figure size
plt.figure(figsize=(12, 6))

# 3. Create a countplot for 'publish_hour'
# Assigning x to hue and setting legend=False to avoid FutureWarning
sns.countplot(x='publish_hour', data=df, hue='publish_hour', palette='viridis', legend=False)

# 4. Add labels and title
plt.xlabel('Hour of Day', fontsize=12)
plt.ylabel('Video Count', fontsize=12)
plt.title('Frequency of Trending Videos by Publish Hour', fontsize=15)

# 5. Display the plot
plt.show()

# Verify the new column and distribution
print("Top 5 Publish Hours by Frequency:")
print(df['publish_hour'].value_counts().head())

"""## Identify Optimal Upload Windows

### Subtask:
Calculate the average 'time_to_trend' or view counts grouped by the publish hour to identify potential 'best' upload time ranges for faster trending or higher reach.

**Reasoning**:
I will calculate the average 'time_to_trend' and 'views' grouped by 'publish_hour' and visualize them using subplots to identify the optimal upload windows.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Group by publish_hour and calculate means for time_to_trend and views
hourly_metrics = df.groupby('publish_hour')[['time_to_trend', 'views']].mean().reset_index()

# 2. Set up the figure with two subplots
fig, axes = plt.subplots(2, 1, figsize=(14, 12))

# 3. Plot Average Time to Trend per Hour
sns.barplot(x='publish_hour', y='time_to_trend', data=hourly_metrics, ax=axes[0], hue='publish_hour', palette='coolwarm', legend=False)
axes[0].set_title('Average Time to Trend by Publish Hour (Lower is Faster)', fontsize=14)
axes[0].set_xlabel('Hour of Day (0-23)', fontsize=12)
axes[0].set_ylabel('Avg Hours to Trend', fontsize=12)

# 4. Plot Average Views per Hour
sns.barplot(x='publish_hour', y='views', data=hourly_metrics, ax=axes[1], hue='publish_hour', palette='viridis', legend=False)
axes[1].set_title('Average Views by Publish Hour (Higher is Better Reach)', fontsize=14)
axes[1].set_xlabel('Hour of Day (0-23)', fontsize=12)
axes[1].set_ylabel('Avg View Count', fontsize=12)

plt.tight_layout()
plt.show()

# Print summary insights
best_speed_hour = hourly_metrics.loc[hourly_metrics['time_to_trend'].idxmin(), 'publish_hour']
best_reach_hour = hourly_metrics.loc[hourly_metrics['views'].idxmax(), 'publish_hour']

print(f"Optimal hour for speed (fastest trending): {int(best_speed_hour)}:00")
print(f"Optimal hour for reach (highest avg views): {int(best_reach_hour)}:00")

"""## Final Task

### Subtask:
Summarize the findings from the timing analysis, highlighting the most common publish hours and the typical speed at which videos reach the trending page.

## Summary:

### Q&A

**What are the most common publish hours for trending videos?**
The most frequent hours for publishing videos that eventually trend are between **11:00 and 14:00 (11 AM - 2 PM)**, with **14:00 (2 PM)** being the absolute peak at 2,838 videos. Another notable peak occurs early in the morning around **06:00 (6 AM)**.

**What is the typical speed at which videos reach the trending page?**
The majority of videos reach the trending page within a short window of **48 to 72 hours** post-upload. While some outliers take thousands of hours, the distribution is heavily right-skewed toward rapid trending.

**Which hours are optimal for speed versus reach?**
*   **Optimal for Speed:** Videos published at **23:00 (11 PM)** tend to reach the trending page the fastest (lowest average time to trend).
*   **Optimal for Reach:** Videos published at **13:00 (1 PM)** achieve the highest average view counts.

### Data Analysis Key Findings

*   **High-Volume Publish Window:** The early afternoon (12 PM - 2 PM) accounts for the largest volume of trending content, with over 8,200 videos published during this 3-hour window alone.
*   **Time-to-Trend Distribution:** The analysis of the first 200 hours shows that the frequency of trending status drops significantly after the initial 72-hour period.
*   **Speed vs. Reach Trade-off:** There is a distinct difference between when videos are most frequently uploaded and when they perform best. While **14:00** is the most popular upload time, **23:00** is more efficient for rapid trending, and **13:00** is superior for total views.
*   **Top 5 Hours by Frequency:**
    *   14:00: 2,838 videos
    *   12:00: 2,782 videos
    *   13:00: 2,631 videos
    *   06:00: 2,323 videos
    *   11:00: 2,295 videos

### Insights or Next Steps

*   **Strategic Scheduling:** Content creators should prioritize uploading around **13:00 (1 PM)** to maximize average view reach, as this falls within the high-frequency window but yields better audience engagement than the 14:00 peak.
*   **Categorical Deep Dive:** A valuable next step would be to correlate these timing patterns with video categories (e.g., Entertainment vs. News) to see if specific genres have different "prime time" windows for trending.

# 5. Correlation Heatmap

# Task
Generate a correlation heatmap to analyze the relationships between numerical engagement metrics in the "/content/INvideos.csv" dataset by performing the following steps:
1. **Select Engagement Metrics**: Extract the numerical columns 'views', 'likes', 'dislikes', and 'comment_count' from the DataFrame.
2. **Calculate Correlation Matrix**: Compute the Pearson correlation matrix for these selected engagement metrics.
3. **Visualize Correlation Heatmap**: Create a seaborn heatmap to visualize the correlation matrix, including annotations, a color map (e.g., 'coolwarm'), and proper formatting for readability.
4. **Summarize Findings**: Summarize the correlation analysis, highlighting which metrics show the strongest relationships and explaining what these correlations imply about audience behavior on the platform.

## Select Engagement Metrics

### Subtask:
Extract the numerical engagement columns 'views', 'likes', 'dislikes', and 'comment_count' from the existing DataFrame `df`.

**Reasoning**:
I will extract the specified numerical engagement columns ('views', 'likes', 'dislikes', 'comment_count') into a new subset DataFrame and display the first few rows to verify the selection.
"""

# Extract the numerical engagement columns
engagement_subset = df[['views', 'likes', 'dislikes', 'comment_count']]

# Display the first five rows to verify extraction
print("Engagement Metrics Subset (First 5 Rows):")
display(engagement_subset.head())

# Confirm the data types
print("\nColumn Data Types:")
print(engagement_subset.dtypes)

"""## Calculate Correlation Matrix

### Subtask:
Compute the Pearson correlation matrix for the selected engagement metrics: 'views', 'likes', 'dislikes', and 'comment_count'.

**Reasoning**:
I will calculate the Pearson correlation matrix for the engagement metrics using the `corr()` method and store it in `corr_matrix` for numerical inspection as requested.
"""

# Calculate the Pearson correlation matrix
corr_matrix = engagement_subset.corr()

# Print the correlation matrix to inspect the values
print("Pearson Correlation Matrix:")
print(corr_matrix)

"""**Reasoning**:
I will visualize the correlation matrix using a seaborn heatmap with annotations and the 'coolwarm' color map to identify relationships between engagement metrics.


"""

import matplotlib.pyplot as plt
import seaborn as sns

# Set the figure size
plt.figure(figsize=(10, 8))

# Create the heatmap
sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm', square=True, linewidths=0.5)

# Add title and labels
plt.title('Correlation Heatmap of Engagement Metrics', fontsize=15)
plt.show()

"""## Summary of Correlation Analysis:

### Q&A

**Which metrics show the strongest relationship?**
The strongest relationship exists between **views and likes (0.85)**, followed closely by **likes and comment_count (0.78)**. This suggests that as a video gets more views, it is highly likely to receive a corresponding increase in likes.

**What does the correlation between dislikes and comment_count imply?**
There is a strong positive correlation between **dislikes and comment_count (0.71)**. This often implies that controversial content (which triggers dislikes) also tends to spark a high volume of discussion in the comments section.

### Data Analysis Key Findings

*   **Engagement Drivers**: Views are most strongly correlated with Likes (0.85), indicating that positive reinforcement is the primary form of engagement as reach grows.
*   **Discussion Triggers**: Comment counts correlate more strongly with Likes (0.78) and Dislikes (0.71) than with total Views (0.67), suggesting that the *intensity* of the reaction (positive or negative) is a better predictor of discussion than just the number of people who saw the video.
*   **General Trends**: All engagement metrics show a positive correlation with each other, meaning that a 'trending' status usually brings a lift across all interaction types simultaneously.

### Insights or Next Steps

*   **Ratio Analysis**: Given the high correlations, analyzing the *ratios* (like-to-view or dislike-to-like) might reveal more about content quality or sentiment than raw numbers alone.
*   **Predictive Modeling**: These strong linear relationships suggest that simple regression models could reasonably predict engagement levels based on early view counts.

## Final Task

### Subtask:
Summarize the correlation analysis findings and their implications for audience behavior.

## Summary:

### Q&A

**Which metrics show the strongest relationship?**  
The strongest relationship exists between **views and likes (0.85)**. This indicates that as a video’s reach increases, positive reinforcement (likes) is the most consistent outcome.

**What does the correlation between dislikes and comment_count imply?**  
There is a strong positive correlation of **0.71** between dislikes and comment counts. This suggests that polarizing or controversial content—which triggers negative reactions—is a significant driver of discussion and activity in the comments section.

### Data Analysis Key Findings

*   **Positive Sentiment and Reach**: Views are most strongly correlated with Likes (**0.85**), meaning that popular videos generally receive high levels of positive affirmation.
*   **Discussion Drivers**: The `comment_count` correlates more strongly with Likes (**0.78**) and Dislikes (**0.71**) than it does with raw Views (**0.67**). This indicates that the emotional intensity of the viewer (whether positive or negative) is a better predictor of engagement in the comments than simple viewership.
*   **Universal Growth**: All engagement metrics show positive Pearson correlation coefficients, demonstrating that "trending" content typically sees a simultaneous lift across all forms of interaction.
*   **Controversy Factor**: The high correlation between dislikes and comments (**0.71**) highlights that negative sentiment does not stifle engagement; rather, it often fuels it through increased conversation.

### Insights or Next Steps

*   **Sentiment Ratio Analysis**: Since raw engagement metrics are highly correlated, next steps should involve analyzing the *ratios* (e.g., Like-to-Dislike or Comment-to-View ratios) to better distinguish between high-quality content and controversial "clickbait."
*   **Early Prediction**: The strong linear relationship between early view counts and engagement suggests that predictive modeling could be used to forecast the ultimate "viral" potential of a video based on its first few hours of data.

# 6. WordCloud (Tags Analysis)

# Task
Analyze the popular keywords and topics in the "/content/INvideos.csv" dataset by performing the following steps:
1. **Prepare Tag Data**: Combine all tags from the 'tags' column into a single large string, ensuring proper handling of missing values or formatting (e.g., stripping extra characters).
2. **Generate WordCloud**: Create a WordCloud object using the combined tags, specifying parameters such as background color, maximum words, and standard stopwords to filter out irrelevant terms.
3. **Visualize WordCloud**: Use matplotlib to display the generated WordCloud with a large figure size, no axes, and a descriptive title for clear visualization.
4. **Final Task**: Summarize the findings from the tag analysis, identifying the most prominent keywords and themes associated with trending videos in the dataset.

## Prepare Tag Data

### Subtask:
Combine all tags from the 'tags' column into a single large string, handling any missing values or formatting needs.

**Reasoning**:
I will prepare the tag data by cleaning the 'tags' column, filtering out placeholder values, and concatenating all tags into a single cleaned string for future analysis.
"""

import pandas as pd

# 1. Handle missing values and filter out '[none]'
# We create a copy to avoid SettingWithCopyWarning
tags_series = df['tags'].fillna('').copy()
tags_filtered = tags_series[tags_series != '[none]']

# 2. Concatenate all remaining tags into one long string with space separation
combined_tags = ' '.join(tags_filtered)

# 3. Clean the resulting string
# Removing double quotes and pipe symbols (|) often used as delimiters
cleaned_tags = combined_tags.replace('"', '').replace('|', ' ')

# 4. Print the first 500 characters to verify formatting
print("First 500 characters of the combined tags string:")
print(cleaned_tags[:500])

# Verify the length of the string
print(f"\nTotal length of the cleaned tags string: {len(cleaned_tags)} characters.")

"""**Reasoning**:
The tag data preparation is complete. Now I will generate the WordCloud using the cleaned tags string and standard stopwords as per the task instructions.


"""

import matplotlib.pyplot as plt
from wordcloud import WordCloud, STOPWORDS

# Initialize the WordCloud object
# Using standard stopwords and setting visual parameters
wc = WordCloud(
    background_color="white",
    max_words=200,
    stopwords=STOPWORDS,
    width=1600,
    height=800
).generate(cleaned_tags)

# Display the WordCloud
plt.figure(figsize=(20, 10))
plt.imshow(wc, interpolation="bilinear")
plt.title("Most Common Tags in Trending Videos", fontsize=24)
plt.axis("off")
plt.show()

print("WordCloud generation and visualization complete.")

"""## Summary of Tag Analysis:

### Q&A

**What are the most prominent themes in the trending video tags?**
The WordCloud reveals that entertainment, news, and regional music (particularly Punjabi and Bollywood) are the most dominant themes. Keywords like "new song", "latest news", "comedy", and "punjabi song" appear frequently, indicating that the Indian trending page is heavily driven by media consumption and current events.

**Are there specific artists or content creators that stand out?**
Yes, certain names like "Sharry Mann" and "Parmish Verma" appear prominently in the tags, reflecting the high popularity of specific regional music artists in the trending dataset during this period.

### Data Analysis Key Findings

*   **Content Pillars**: The primary drivers for trending status in India appear to be Music, News, and Entertainment (Comedy/Bollywood).
*   **Regional Dominance**: Punjabi music and entertainment have a significant footprint in the trending tags, often appearing alongside more general Bollywood keywords.
*   **Timeliness**: Words like "2017", "2018", "latest", and "new" are highly frequent, emphasizing that the trending algorithm prioritizes fresh, timely content.
*   **News Consumption**: Terms like "breaking news", "today news", and "current news" highlight that YouTube serves as a major platform for news dissemination in the region.

### Insights or Next Steps

*   **Stopword Refinement**: Future analysis could involve adding domain-specific stopwords (like "video", "song", "new") to uncover deeper, more specific sub-genres or niche topics.
*   **Cross-Reference with Categories**: Comparing these word clouds across different `category_id` values would help determine if certain keywords are universal or specific to certain types of content (e.g., does "comedy" appear in News tags?).

## Final Task

### Subtask:
Summarize the findings from the tag analysis, identifying the most prominent keywords and themes associated with trending videos in the dataset.

## Summary:

### Q&A

**What are the most prominent themes identified in the trending video tags?**
The analysis reveals that Entertainment, News, and Regional Music (specifically Punjabi and Bollywood) are the dominant themes. High-frequency keywords include "new song," "latest news," "comedy," and "punjabi song."

**Are there specific artists or content creators that frequently appear in the tags?**
Yes, regional music artists such as "Sharry Mann" and "Parmish Verma" appear prominently, indicating their significant influence on the trending charts within the Indian dataset.

### Data Analysis Key Findings

*   **Massive Data Volume**: The processed tag data resulted in a massive text string of approximately 10,955,563 characters, showcasing the high volume of metadata associated with trending videos.
*   **Regional Music Influence**: Punjabi music has a massive footprint in the Indian trending landscape, often appearing as frequently as mainstream Bollywood content.
*   **News as a Trending Pillar**: YouTube is a primary source for news consumption in India, evidenced by the high density of tags like "breaking news," "today news," and "current news."
*   **Recency Bias**: The trending algorithm shows a strong preference for fresh content, as highlighted by the dominance of keywords like "2017," "2018," "latest," and "new."
*   **Specific Content Tags**: Beyond music and news, "comedy" remains a staple tag, indicating that humor is a consistent driver for viral potential in the region.

### Insights or Next Steps

*   **Enhanced Filtering**: To uncover niche trends, future analysis should implement a custom stopword list to remove generic terms like "video," "song," and "latest," which currently dominate the visualization.
*   **Categorical Segmentation**: Performing tag analysis specifically within individual category IDs (e.g., Gaming vs. Education) would reveal whether certain keywords are universal or unique to specific content genres.

# 7. K-Means Clustering

# Task
Perform K-Means clustering on the "/content/INvideos.csv" dataset to segment videos based on engagement by following these steps:
1. **Prepare and Scale Features**: Select the 'views', 'likes', and 'comment_count' columns and normalize them using `StandardScaler` to ensure the clustering algorithm treats them equally.
2. **Determine Optimal Clusters**: Use the Elbow Method by calculating and plotting the Within-Cluster Sum of Squares (WCSS) for 1 to 10 clusters to identify the ideal number of groupings.
3. **Apply K-Means**: Train the KMeans model with the optimal cluster count, fit it to the scaled data, and append the resulting cluster labels to your original DataFrame.
4. **Visualize Results**: Generate a scatter plot (e.g., Views vs. Likes) colored by the cluster labels to visualize how the videos are segmented.
5. **Summarize Findings**: Describe the characteristics of each identified cluster (e.g., distinguishing between high-engagement viral hits and low-engagement videos) and analyze the distribution of videos across these groups.

## Prepare and Scale Features

### Subtask:
Select the 'views', 'likes', and 'comment_count' columns from the existing DataFrame and normalize them using `StandardScaler` for clustering.

**Reasoning**:
I will select the required numerical columns, import StandardScaler, and perform normalization to prepare the data for clustering.
"""

from sklearn.preprocessing import StandardScaler

# 1. Select the relevant features
clustering_subset = df[['views', 'likes', 'comment_count']]

# 2. Instantiate and apply StandardScaler
scaler = StandardScaler()
scaled_features = scaler.fit_transform(clustering_subset)

# 3. Print verification info
print(f"Shape of scaled_features: {scaled_features.shape}")
print("\nFirst 5 rows of original subset for verification:")
display(clustering_subset.head())

# 4. Show a sample of the scaled data
print("\nFirst 2 rows of scaled data:")
print(scaled_features[:2])

"""## Elbow Method for Optimal Clusters

### Subtask:
Iterate through a range of cluster counts (1 to 10) and calculate the Within-Cluster Sum of Squares (WCSS) to identify the optimal number of clusters.

**Reasoning**:
I will perform the Elbow Method by iterating through cluster counts from 1 to 10, calculating the Within-Cluster Sum of Squares (WCSS) using KMeans, and plotting the results to identify the optimal number of clusters.
"""

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

# 1. Initialize an empty list to store the inertia values (WCSS)
wcss = []

# 2. Iterate through a range of cluster counts (1 to 10)
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42)
    kmeans.fit(scaled_features)
    wcss.append(kmeans.inertia_)

# 3. Plot the Elbow Method results
plt.figure(figsize=(10, 6))
plt.plot(range(1, 11), wcss, marker='o', linestyle='--', color='blue')

# 4. Add labels and title
plt.title('Elbow Method for Optimal Clusters', fontsize=15)
plt.xlabel('Number of Clusters', fontsize=12)
plt.ylabel('WCSS (Inertia)', fontsize=12)
plt.xticks(range(1, 11))
plt.grid(True)

# 5. Display the plot
plt.show()

print("WCSS values per cluster count:")
for i, val in enumerate(wcss, 1):
    print(f"Clusters {i}: {val:.2f}")

"""## Apply K-Means Clustering

### Subtask:
Train the KMeans model with the optimal cluster count, fit it to the scaled data, and append the resulting cluster labels to the original DataFrame.

**Reasoning**:
I will train the KMeans model with the optimal cluster count of 4, fit it to the scaled features, and append the resulting labels to the DataFrame 'df' under a new 'cluster' column as specified in the instructions.
"""

from sklearn.cluster import KMeans

# 1. Instantiate the KMeans model with n_clusters=4
kmeans = KMeans(n_clusters=4, init='k-means++', random_state=42)

# 2. Fit the model to the scaled_features and predict cluster labels
df['cluster'] = kmeans.fit_predict(scaled_features)

# 3. Display the first few rows focusing on engagement metrics and the new cluster column
print("K-Means clustering complete. Cluster labels assigned.")
display(df[['views', 'likes', 'comment_count', 'cluster']].head())

# 4. Check the distribution of videos across clusters
print("\nNumber of videos per cluster:")
print(df['cluster'].value_counts())

"""## Visualize Clusters

### Subtask:
Create a scatter plot to visualize the K-Means clustering results based on video engagement.

**Reasoning**:
I will create a scatter plot using seaborn to visualize the results of the K-Means clustering, plotting views against likes and coloring the points by their assigned cluster label to show the engagement segments.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Set the visual style
sns.set_style('whitegrid')

# Initialize the figure
plt.figure(figsize=(12, 8))

# Create the scatter plot
# x='views', y='likes', colored by 'cluster'
sns.scatterplot(data=df, x='views', y='likes', hue='cluster', palette='viridis', alpha=0.7, s=60)

# Add title and clear labels
plt.title('Video Engagement Clusters: Views vs. Likes', fontsize=16)
plt.xlabel('Total Views', fontsize=12)
plt.ylabel('Total Likes', fontsize=12)

# Add a legend to explain the clusters
plt.legend(title='Cluster ID', loc='upper left')

# Display the plot
plt.show()

"""## Final Task

### Subtask:
Summarize the clustering results, describing the characteristics of each identified group and explaining the distribution of videos across these segments.

## Summary:

### Q&A

**What are the characteristics of the identified clusters?**
Based on the engagement metrics (views, likes, and comment counts), the four clusters represent distinct levels of popularity:
*   **Cluster 0 (Standard/Low Engagement):** The largest group (35,774 videos) consisting of typical content with relatively low views and likes compared to the rest of the dataset.
*   **Cluster 3 (Moderate Engagement):** A mid-tier group of 1,412 videos that performed better than average but did not reach viral status.
*   **Cluster 1 (High Engagement):** A smaller group of 153 videos representing high-performing content with significant reach.
*   **Cluster 2 (Extreme Viral Hits):** A tiny elite group of only 13 videos. these are the extreme outliers with the highest views, likes, and comments in the entire dataset.

### Data Analysis Key Findings

*   **Optimal Cluster Identification:** The Elbow Method revealed a sharp decrease in Within-Cluster Sum of Squares (WCSS) until 3 or 4 clusters, after which the rate of improvement slowed significantly. 4 clusters were chosen for the final model.
*   **Engagement Imbalance:** There is a massive disparity in how videos perform. Cluster 0 contains approximately 95.8% of the dataset (35,774 out of 37,352 videos), indicating that the vast majority of content does not achieve high engagement.
*   **Identification of Outliers:** The K-Means algorithm effectively isolated "Viral Hits" (Cluster 2), which comprises only 0.03% of the data.
*   **Correlation Alignment:** The scatter plot of Views vs. Likes showed a strong positive correlation, and the clustering labels successfully segmented the data points along this trend line, confirming that the model captured the inherent structure of the engagement data.

### Insights or Next Steps

*   **Further Analysis of Viral Content:** Investigate the specific categories, tags, or publishing times of the 13 videos in Cluster 2 to understand what drivers lead to extreme viral success.
*   **Refine Mid-Tier Segmentation:** Since the majority of videos fall into Cluster 0, a secondary clustering process could be performed specifically on that group to distinguish between "underperforming" and "steadily growing" content.
"""